/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package distributoredibevande.gui.panels;

import distributoredibevande.logic.entities.Bevanda;
import distributoredibevande.logic.entities.BevandaCalda;
import distributoredibevande.logic.entities.Distributore;
import distributoredibevande.logic.exceptions.EndedQuantityExceptions;
import distributoredibevande.logic.events.EventManager;
import distributoredibevande.logic.events.TastierinoListener;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author loren
 */
public class SelectorPanel extends javax.swing.JPanel implements TastierinoListener {

    /**
     * Creates new form SelectorPanel
     */
    private boolean caldo = true;
    private boolean error = false;

    public void setCaldo(boolean caldo) {
        this.caldo = caldo;
        if (caldo) {
            this.setBackground(new Color(239, 139, 52));
            this.JpanelTastierinoContainer.setBackground(new Color(239, 139, 52));
            this.jPanel3.setBackground(new Color(239, 139, 52));
            this.jPanel1.setBackground(new Color(203, 100, 10));
        } else {
            this.setBackground(new Color(17, 121, 255));
            this.JpanelTastierinoContainer.setBackground(new Color(17, 121, 255));
            this.jPanel3.setBackground(new Color(17, 121, 255));
        }
    }

    public boolean isCaldo() {
        return caldo;
    }

    public SelectorPanel() {
        initComponents();
        for (int i = 1; i < 10; i++) {
            this.JpanelTastierinoContainer.add(new TastierinoPanel(i));
        }
       // EventManager.getInstance().addTastierinoListener(this);
    }

    public void register(){
        EventManager.getInstance().addTastierinoListener(this);
    }
    
    public void deregister(){
        EventManager.getInstance().removeTastierinoListener(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JpanelTastierinoContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 0));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        JpanelTastierinoContainer.setBackground(new java.awt.Color(204, 204, 204));
        JpanelTastierinoContainer.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("ANNULLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CONFERMA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpanelTastierinoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpanelTastierinoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.jLabel1.getText().equals("-")) {
            this.jLabel1.setText("ERRORE: Nessuna selezione");
            return;
        }
        try {
            int parseInt = Integer.parseInt(this.jLabel1.getText());
            Bevanda b = null;
            if (caldo) {
                b = Distributore.getInstance().selectBevandaCalda(parseInt);
            } else {
                b = Distributore.getInstance().selectBevandaFredda(parseInt);
            }
            this.jLabel1.setText("€ " + b.getPrezzo());
            this.jButton2.setEnabled(false);
        } catch (EndedQuantityExceptions ex) {
            this.error = true;
            this.jLabel1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jLabel1.setText("-");
        this.jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void resetLabel(){
        this.jLabel1.setText("-");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelTastierinoContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void buttonSelected(int numero) {
        if (error) {
            this.jLabel1.setText("" + numero);
            error= false;
        }
        else if (this.jLabel1.getText().equals("-") || this.jLabel1.getText().startsWith("ERRORE") || this.jLabel1.getText().startsWith("€ ")) {
            this.jLabel1.setText("" + numero);
        } else {
            this.jLabel1.setText(this.jLabel1.getText() + numero);
        }
        this.jButton2.setEnabled(true);
    }

    @Override
    public void confirmSelected(int selezione) {
    }
}
